theme: jekyll-theme-cayman
lang: "pt-BR"
description: "Criar esta lista foi a maneira que eu encontrei para organizar todos os meus projetos aqui do GitHub."
title: "Índice de Projetos"
tagline: "GitHub"
